10-21 10:43:58 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "OTC" nicht gefunden
Column "OTC" not found; SQL statement:
CREATE USER otc PASSWORD otc [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:134)
	at org.h2.command.ddl.CreateUser.getCharArray(CreateUser.java:51)
	at org.h2.command.ddl.CreateUser.update(CreateUser.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:662)
10-21 10:44:15 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "OTC" nicht gefunden
Column "OTC" not found; SQL statement:
CREATE USER otc PASSWORD otc [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:134)
	at org.h2.command.ddl.CreateUser.getCharArray(CreateUser.java:51)
	at org.h2.command.ddl.CreateUser.update(CreateUser.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:662)
10-21 10:44:25 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "OTC" nicht gefunden
Column "OTC" not found; SQL statement:
CREATE USER otc PASSWORD otc [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:134)
	at org.h2.command.ddl.CreateUser.getCharArray(CreateUser.java:51)
	at org.h2.command.ddl.CreateUser.update(CreateUser.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:662)
10-21 10:54:15 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Benutzer "OTC" nicht gefunden
User "OTC" not found; SQL statement:
drop user otc [90032-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.DropUser.update(DropUser.java:44)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:662)
10-21 10:54:57 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "OTC" nicht gefunden
Column "OTC" not found; SQL statement:
CREATE USER  "otc" PASSWORD otc [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:134)
	at org.h2.command.ddl.CreateUser.getCharArray(CreateUser.java:51)
	at org.h2.command.ddl.CreateUser.update(CreateUser.java:78)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:662)
10-21 11:14:07 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feature not supported: "clientInfoProperties" [50100-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:204)
	at org.h2.message.TraceObject.unsupported(TraceObject.java:391)
	at org.h2.jdbc.JdbcDatabaseMetaData.getClientInfoProperties(JdbcDatabaseMetaData.java:2806)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.sourceforge.squirrel_sql.fw.sql.MetaDataDataSet.executeGetter(MetaDataDataSet.java:255)
	at net.sourceforge.squirrel_sql.fw.sql.MetaDataDataSet.generateLine(MetaDataDataSet.java:222)
	at net.sourceforge.squirrel_sql.fw.sql.MetaDataDataSet.load(MetaDataDataSet.java:149)
	at net.sourceforge.squirrel_sql.fw.sql.MetaDataDataSet.<init>(MetaDataDataSet.java:96)
	at net.sourceforge.squirrel_sql.fw.sql.MetaDataDecoratorDataSet.<init>(MetaDataDecoratorDataSet.java:73)
	at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.database.MetaDataTab.createDataSet(MetaDataTab.java:74)
	at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.BaseDataSetTab$1.run(BaseDataSetTab.java:123)
	at net.sourceforge.squirrel_sql.fw.util.TaskExecuter.run(TaskExecuter.java:82)
	at java.lang.Thread.run(Thread.java:662)
10-21 11:32:13 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feature not supported: "clientInfoProperties" [50100-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.message.DbException.getUnsupportedException(DbException.java:204)
	at org.h2.message.TraceObject.unsupported(TraceObject.java:391)
	at org.h2.jdbc.JdbcDatabaseMetaData.getClientInfoProperties(JdbcDatabaseMetaData.java:2806)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at net.sourceforge.squirrel_sql.fw.sql.MetaDataDataSet.executeGetter(MetaDataDataSet.java:255)
	at net.sourceforge.squirrel_sql.fw.sql.MetaDataDataSet.generateLine(MetaDataDataSet.java:222)
	at net.sourceforge.squirrel_sql.fw.sql.MetaDataDataSet.load(MetaDataDataSet.java:149)
	at net.sourceforge.squirrel_sql.fw.sql.MetaDataDataSet.<init>(MetaDataDataSet.java:96)
	at net.sourceforge.squirrel_sql.fw.sql.MetaDataDecoratorDataSet.<init>(MetaDataDecoratorDataSet.java:73)
	at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.database.MetaDataTab.createDataSet(MetaDataTab.java:74)
	at net.sourceforge.squirrel_sql.client.session.mainpanel.objecttree.tabs.BaseDataSetTab$1.run(BaseDataSetTab.java:123)
	at net.sourceforge.squirrel_sql.fw.util.TaskExecuter.run(TaskExecuter.java:82)
	at java.lang.Thread.run(Thread.java:662)
10-21 11:51:51 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Unbekannter Datentyp: "FOREIGN"
Unknown data type: "FOREIGN"; SQL statement:
CREATE TABLE IMPORTED ( ID INT PRIMARY KEY , ID_FK_ATHLETE FOREIGN KEY(ID) REFERENCES TEST(ID)) [50004-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:3643)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:3506)
	at org.h2.command.Parser.parseCreateTable(Parser.java:5163)
	at org.h2.command.Parser.parseCreate(Parser.java:3800)
	at org.h2.command.Parser.parsePrepared(Parser.java:324)
	at org.h2.command.Parser.parse(Parser.java:279)
	at org.h2.command.Parser.parse(Parser.java:251)
	at org.h2.command.Parser.prepareCommand(Parser.java:217)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1119)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:662)
10-21 11:53:48 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "ORDERS" nicht gefunden
Table "ORDERS" not found; SQL statement:
ALTER TABLE ORDERS
ADD FOREIGN KEY (ID_FK_ATHLETE ) REFERENCES ATHLETE (SID) [42102-160]
10-21 11:53:57 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Feld "SID" nicht gefunden
Column "SID" not found; SQL statement:
ALTER TABLE IMPORTED 
ADD FOREIGN KEY (ID_FK_ATHLETE ) REFERENCES ATHLETE (SID) [42122-160]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.table.Table.getColumn(Table.java:595)
	at org.h2.table.IndexColumn.mapColumns(IndexColumn.java:75)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:196)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:68)
	at org.h2.command.CommandContainer.update(CommandContainer.java:73)
	at org.h2.command.Command.executeUpdate(Command.java:219)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1311)
	at org.h2.server.web.WebApp.query(WebApp.java:1001)
	at org.h2.server.web.WebApp$1.next(WebApp.java:964)
	at org.h2.server.web.WebApp$1.next(WebApp.java:953)
	at org.h2.server.web.WebThread.process(WebThread.java:166)
	at org.h2.server.web.WebThread.run(WebThread.java:93)
	at java.lang.Thread.run(Thread.java:662)
10-21 11:55:25 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Tabelle "TEST" nicht gefunden
Table "TEST" not found; SQL statement:
ALTER TABLE TEST ADD IMPORTED_DATE TIMESTAMP [42102-160]
